load("@rules_cc//cc:defs.bzl", "cc_test")

cc_test(
    name = "variadic_c",
    srcs = ["variadic_c.cc"],
    deps = [
        "@googletest//:gtest_main",
    ],
)

cc_test(
    name = "variadic_c2",
    srcs = ["variadic_c2.cc"],
    deps = [
        "@googletest//:gtest_main",
    ],
)
